services:
  - type: web
    name: crop-soil-predictor
    runtime: python
    buildCommand: pip install -r requirements.txt && python -c "from main import train_models; train_models()"
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
