services:
  - type: web
    name: crop-soil-predictor
    runtime: python
    buildCommand: pip install -r requirements.txt && python main.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
