services:
  - type: web
    name: crop-soil-predictor
    runtime: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt && python -c "from main import train_models; train_models()"
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
